Shopping Cart API endpoints and dummy JSON
PiotrKolecki/team-programming-game-shop pull request #13
Opened 2021-04-14 17:55 UTC by Szy11mon

2021-04-14 19:41 UTC, PiotrKolecki commented
Please ask for review

2021-04-14 21:19 UTC, DorianKossowski requested changes

2021-04-14 21:19 UTC, DorianKossowski commented on shopping-cart-service/src/main/java/agh/fis/shopping_cart/controller/ShoppingCartController.java
> +        return message;
Maybe try to use a data transfer object (ShoppingCartDto?) with fields like ids and a set of items or something like this.  It's not important at this stage to return some real data but to have some structures that will be visible in API. You can try with OpenAPI as I mentioned on Teams

2021-04-14 21:19 UTC, DorianKossowski commented on shopping-cart-service/src/main/java/agh/fis/shopping_cart/controller/ShoppingCartController.java
> +        return String.format("Cart with id %s created", 3);
Try to return DTO from methods not Strings

2021-04-15 04:42 UTC, PawelKepka approved these changes

2021-04-26 19:20 UTC, DorianKossowski commented on shopping-cart-service/src/main/resources/api.yaml
> +        products:
Probably cusomerId should be enough

2021-04-27 14:31 UTC, DorianKossowski approved these changes

2021-04-27 15:05 UTC, merged