Product catalog
PiotrKolecki/team-programming-game-shop pull request #16
Opened 2021-04-15 09:38 UTC by PawelKepka

2021-04-15 09:49 UTC, Szy11mon submitted a review, later dismissed

2021-04-19 10:12 UTC, PiotrKolecki requested changes
Try not to remove String in sesponse. Try using OpenAPI

2021-05-05 18:35 UTC, Szy11mon reviewed
It looks like ProductCatalogController doesn't use API defined with the usage of OpenAPI in this PR. Methods should return ResponseEntity, not strings. There is no need of importing PostMapping, PutMapping etc. as it this defined in api.yaml file. It looks like those changes are made in https://github.com/PiotrKolecki/team-programming-game-shop/pull/27, so this PR should probably be closed.

2021-06-12 12:59 UTC, closed without merging

2021-06-12 12:59 UTC, PawelKepka commented
Closer